#!/usr/bin/env bash
# Rebuilds a runnable JAWEBNI environment inside the sandbox.
#
# The sandbox has no native PHP, no Composer and no Packagist access, so the
# stack is booted differently:
#   * PHP 8.3 runs as WebAssembly through @php-wasm/node
#   * vendor/ is rebuilt from composer.lock via GitHub zipballs
#   * the Composer autoloader is generated by make-autoload.mjs (no proc_open)
#
# Usage:  bash sandbox-tools/bootstrap.sh     # build only
#         bash sandbox-tools/serve.sh         # build + serve on 0.0.0.0:8000
set -e
export NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt

PROJECT=/home/user/JAWEBNI
TOOLS=$PROJECT/sandbox-tools
cd "$PROJECT"

echo "== 1/6 php-wasm toolchain =="
[ -d "$TOOLS/node_modules" ] || (cd "$TOOLS" && npm install --no-audit --no-fund)

echo "== 2/6 vendor (composer.lock -> GitHub zipballs) =="
[ -f "$PROJECT/vendor/autoload.php" ] || (cd "$TOOLS" && node install-vendor.mjs)

echo "== 3/6 autoloader (psr-4 / psr-0 / classmap / files) =="
(cd "$TOOLS" && node make-autoload.mjs)

echo "== 4/6 env + app key =="
[ -f "$PROJECT/.env" ] || cp "$PROJECT/.env.example" "$PROJECT/.env"
mkdir -p "$PROJECT/database" && touch "$PROJECT/database/database.sqlite"
grep -q "^APP_KEY=base64:" "$PROJECT/.env" || (cd "$TOOLS" && node run.mjs artisan key:generate --force)

echo "== 5/6 migrate + seed =="
(cd "$TOOLS" && node run.mjs artisan migrate --force --seed)

echo "== 6/6 frontend assets =="
[ -d "$PROJECT/node_modules" ] || npm install --no-audit --no-fund
[ -f "$PROJECT/public/build/manifest.json" ] || npm run build

echo "== ready =="
echo "Start the app with:  node sandbox-tools/server.mjs   (listens on 0.0.0.0:8000)"
